site_name: NH Switch Guide
theme: slate
copyright: Copyright &copy; 2023 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, forked from the original by the <a href="/switch-guide/about">NH Discord Server</a>. This fork maintained by <a href="https://github.com/Wi-Fi-Labs" target="_blank">PS! Wi-Fi Labs</a>.
site_description: Switch CFW Guide.
site_author: NH Discord Server.
site_url: https://nh-server.github.io/switch-guide/

nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - 'RCM': 'user_guide/rcm.md'  
        - 'SD preparations': 'user_guide/sysnand/sd_preparation.md'
        - 'Entering RCM': 'user_guide/sysnand/entering_rcm.md'
        - 'Sending a payload': 'user_guide/sysnand/sending_payload.md'      
        - 'Making essential backups': 'user_guide/sysnand/making_essential_backups.md'    
        - 'Launching CFW': 'user_guide/sysnand/launching_cfw.md'
    - Extras:
        - 'Blocking Nintendo servers': 'extras/blocking_nintendo.md'
        - 'Restoring a NAND Backup': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Theming': 'extras/theming.md'
        - 'Save Management': 'extras/save_management.md'
        - 'Game Modding': 'extras/game_modding.md'
        - 'Game Cheats': 'extras/cheats.md'
        - 'Linux injection without root': 'extras/adding_udev.md'
        - 'Showing File Name Extensions (Windows)': 'extras/showing_file_extensions.md'
        - 'Alternate Boot Setups': 'extras/alternate_bootsetups.md'
        - 'RCM Payload Injectors Information': 'extras/rcm_injectors.md'
        - 'Updating CFW': 'extras/updating.md'
        - 'Changing SD cards': 'extras/transfer_sd.md'
        - 'Glossary': 'extras/glossary.md'
    - FAQ: faq.md
    - About: about.md
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css
